name: Deploy Notification

# Executa quando hรก push ou pull request na branch master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Call deploy endpoint
      run: |
        echo "Calling deploy endpoint..."
        curl -X GET "http://206.183.131.104:3000/api/box/deploy/1badc58682faee248ccf" \
          -H "Content-Type: application/json" \
          -w "\nHTTP Status: %{http_code}\n" \
          -s
        echo "Deploy notification sent successfully!"
      shell: bash 